[tool.poetry]
name = "jsonpath"
version = "0.1.0"
description = ""
authors = ["林玮 <linw1995@icloud.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
sly = "^0.3.0"

black = {version = "^19.3b0", optional = true}
flake8 = {version = "^3.7.8", optional = true}
isort = {version = "^4.3.21", optional = true}
pytest = {version = "^5.2.0", optional = true}
pytest-cov = {version = "^2.7.1", optional = true}
flake8-bugbear = {version = "^19.8", optional = true}

[tool.poetry.dev-dependencies]
rope = {version = "^0.14.0"}
pre-commit = "^1.20"

[tool.poetry.extras]
linting = ["black", "flake8", "flake8-bugbear", "isort", "pytest"]
test = ["pytest", "pytest-cov"]

[tool.black]
line-length = 80
target-version = ['py38']
include = '\.pyi?$'
exclude = '''

(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
  | foo.py           # also separately exclude a file named foo.py in
                     # the root of the project
)
'''


[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
